import {
  AfterInsert,
  AfterRemove,
  AfterUpdate,
  Column,
  Entity,
  PrimaryGeneratedColumn,
  Unique,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

export enum UserRole {
  ADMIN = 'sysadmin',
  CUSTOMER = 'customer',
}
@Entity()
@Unique(['email'])
export class User {
  // user's autogenerated id
  @PrimaryGeneratedColumn()
  id: number;

  // user's first name
  @Column({ type: 'varchar', length: 200, nullable: false })
  first_name: string;

  // user's last name
  @Column({ type: 'varchar', length: 200, nullable: false })
  last_name: string;

  @Column({
    type: 'varchar',
    unique: true,
    length: 200,
    nullable: false,
  })
  email: string;

  @Column({ type: 'varchar', length: 200, nullable: false })
  password: string;

  @Column({
    type: 'enum',
    enum: UserRole,
    default: UserRole.CUSTOMER,
    nullable: false,
  })
  role: UserRole;

  @CreateDateColumn({
    type: 'timestamp',
    default: () => 'CURRENT_TIMESTAMP(6)',
    nullable: false,
  })
  created_at: Date;

  @UpdateDateColumn({
    type: 'timestamp',
    default: () => 'CURRENT_TIMESTAMP(6)',
    onUpdate: 'CURRENT_TIMESTAMP(6)',
    nullable: false,
  })
  updated_at: Date;

  @Column({
    type: 'boolean',
    default: false,
    nullable: false,
  })
  is_email_verified: boolean;

  @AfterInsert()
  logInsert() {
    console.log('User inserted:', this);
  }

  @AfterUpdate()
  logUpdate() {
    console.log('User updated:', this);
  }

  @AfterRemove()
  logRemove() {
    console.log('User removed:', this);
  }
}
